version: '3.7'

services:
  db_postregs:
    image: bitnami/postgresql:latest
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ms-email
